export const categories = [
  { id: '1', name: 'Biryani', icon: '🍛' },
  { id: '2', name: 'Burger', icon: '🍔' },
  { id: '3', name: 'Pizza', icon: '🍕' },
  { id: '4', name: 'Desserts', icon: '🍰' },
  { id: '5', name: 'Chinese', icon: '🥡' },
  { id: '6', name: 'Italian', icon: '🍝' },
  { id: '7', name: 'Thai', icon: '🍜' },
  { id: '8', name: 'Mexican', icon: '🌮' },
];

export const kitchens = [
  {
    id: '1',
    name: 'Spice Kitchen',
    description: 'Authentic Indian cuisine',
    logo: '🏪',
    address: '123 Main St, Dhaka',
    rating: 4.5,
    deliveryTime: '25-35 min',
  },
  {
    id: '2',
    name: 'Burger Hub',
    description: 'Juicy burgers and fries',
    logo: '🏪',
    address: '456 Oak Ave, Dhaka',
    rating: 4.2,
    deliveryTime: '20-30 min',
  },
  {
    id: '3',
    name: 'Pizza Palace',
    description: 'Wood-fired pizzas',
    logo: '🏪',
    address: '789 Pine Rd, Dhaka',
    rating: 4.7,
    deliveryTime: '30-40 min',
  },
  {
    id: '4',
    name: 'Sweet Treats',
    description: 'Delicious desserts',
    logo: '🏪',
    address: '321 Elm St, Dhaka',
    rating: 4.3,
    deliveryTime: '15-25 min',
  },
  {
    id: '5',
    name: 'Wok Express',
    description: 'Quick Chinese food',
    logo: '🏪',
    address: '654 Maple Dr, Dhaka',
    rating: 4.1,
    deliveryTime: '20-30 min',
  },
  {
    id: '6',
    name: 'Pasta Corner',
    description: 'Italian pasta dishes',
    logo: '🏪',
    address: '987 Cedar Ln, Dhaka',
    rating: 4.6,
    deliveryTime: '25-35 min',
  },
];